// <auto-generated />
namespace SimpleAccounting.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class praneetthakur_2_for_logo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(praneetthakur_2_for_logo));
        
        string IMigrationMetadata.Id
        {
            get { return "201709080720103_praneetthakur_2_for_logo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
